<a href="https://colab.research.google.com/github/ozgurgungor1/NumPy-ogreniyorum/blob/main/Youtube_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ders - 1 Numpy Kurulumu

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

# Ders - 2 Numpy ile Nokta Doğru Düzlem ve Uzay

In [ ]:
skaler=np.array(90)
print(skaler)

90


In [ ]:
vektor=np.array([1,2,3,4,5,6])
print(vektor)

[1 2 3 4 5 6]


In [ ]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
tensor=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Ders - 3 Neden Numpy ?

In [ ]:
import time

In [ ]:
z1=time.time()

liste=[]
for a in range(1_000_000):
  kuvvet=a**100
  liste.append(kuvvet)

z2=time.time()

print(z2-z1)

2.1779305934906006


In [ ]:
z3=time.time()

liste2=np.arange(1_000_000)**100

z4=time.time()

print(z4-z3)

0.02458357810974121


# Ders 4 Index ve Slice

In [ ]:
vektor=np.array([0,2,4,5,6,7,8,15])

In [ ]:
vektor[3]

5

In [ ]:
vektor[0]

0

In [ ]:
vektor[-1]

15

In [ ]:
vektor[1:3]

array([2, 4])

In [ ]:
vektor[:5]

array([0, 2, 4, 5, 6])

In [ ]:
vektor[2:6:2]

array([4, 6])

# Ders 5 Size,Shape,Dtype,ndim

In [ ]:
vektor=np.array([1,2,3,4,5,6])
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(vektor)

[1 2 3 4 5 6]


In [ ]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
vektor.size

6

In [ ]:
matris.size

9

In [ ]:
vektor.shape

(6,)

In [ ]:
matris.shape

(3, 3)

In [ ]:
vektor.ndim

1

In [ ]:
matris.ndim

2

In [ ]:
vektor.dtype

dtype('int64')

In [ ]:
matris.dtype

dtype('int64')

In [ ]:
type(vektor)

numpy.ndarray

In [ ]:
type(matris)

numpy.ndarray

# Ders6 - Numpy Veri Tipi Değiştirme

In [ ]:
sayilar=np.array([1,2,3,4,5,6])

In [ ]:
sayilar.dtype

dtype('int64')

In [ ]:
sayilar=np.array([1,2,3,4,5.0,6])
sayilar.dtype

dtype('float64')

In [ ]:
sayilar=sayilar.astype("int8")
sayilar.dtype

dtype('int8')

In [ ]:
sayilar=np.array([1,2,3,4,5,6],dtype="int8")
sayilar.dtype

dtype('int8')

In [ ]:
tarih=np.array(["2023-01-01"])
tarih.dtype

dtype('<U10')

In [ ]:
tarih=tarih.astype("datetime64[ns]")
tarih.dtype

dtype('<M8[ns]')

# Ders 7 Matrislerde Slice

In [ ]:
matris=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [ ]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
matris[0]

array([1, 2, 3, 4])

In [ ]:
matris[1]

array([5, 6, 7, 8])

In [ ]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
matris[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [ ]:
matris[0:4,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

# Ders 8 - Random Matris Oluşturma

In [ ]:
dir(np.random)

In [ ]:
np.random.randint(0,5,(4,4))

array([[2, 3, 4, 2],
       [3, 2, 4, 3],
       [3, 3, 2, 4],
       [1, 3, 0, 1]])

In [ ]:
np.random.randint(0,10,(4,4))/10

array([[0.2, 0.6, 0.7, 0.2],
       [0.1, 0.7, 0.8, 0.4],
       [0.1, 0.3, 0.7, 0.6],
       [0.6, 0.2, 0.2, 0.4]])

# Ders 9 - Arange ile Vektör Oluşturma

In [ ]:
liste=[1,2,3,4,5,6]
range(1000000)

range(0, 1000000)

In [ ]:
milyon=np.arange(1000000)

In [ ]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

# Ders 10 - linspace() ile Vektör Oluşturma

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

In [ ]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [ ]:
bol=np.linspace(5,25,15)

In [ ]:
bol

array([ 5.        ,  6.42857143,  7.85714286,  9.28571429, 10.71428571,
       12.14285714, 13.57142857, 15.        , 16.42857143, 17.85714286,
       19.28571429, 20.71428571, 22.14285714, 23.57142857, 25.        ])

In [ ]:
bol[5]-bol[4]

1.428571428571427

# Ders 11 Numpy Yeniden Boyutlandırma reshape() Metodu

In [ ]:
m1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m1.shape

(3, 4)

In [ ]:
m1.size

12

In [ ]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
m1x=m1.reshape(12)

In [ ]:
m1x.shape

(12,)

In [ ]:
np.random.randint(0,2,(8,6)).reshape(4,12)

array([[0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1]])

In [ ]:
np.linspace(0,20,30).reshape(6,5)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069],
       [ 3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655],
       [ 6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241],
       [10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828],
       [13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414],
       [17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ]])

# Ders 12 copy() ve View() Metotları

In [ ]:
import numpy as np

In [ ]:
matris=np.random.randint(0,5,(4,4))

In [ ]:
matris

array([[4, 4, 0, 4],
       [0, 1, 4, 3],
       [4, 4, 1, 4],
       [1, 3, 0, 4]])

In [ ]:
matris2=matris.view()

In [ ]:
matris2[0]=[9,9,9,9]

In [ ]:
matris2

array([[9, 9, 9, 9],
       [0, 1, 4, 3],
       [4, 4, 1, 4],
       [1, 3, 0, 4]])

In [ ]:
matris

array([[9, 9, 9, 9],
       [0, 1, 4, 3],
       [4, 4, 1, 4],
       [1, 3, 0, 4]])

In [ ]:
matris3=np.random.randint(0,5,(4,4))

In [ ]:
matris3

array([[4, 4, 4, 0],
       [2, 2, 4, 1],
       [1, 3, 3, 1],
       [1, 4, 2, 3]])

In [ ]:
matris4=matris3.copy()

In [ ]:
matris4

array([[4, 4, 4, 0],
       [2, 2, 4, 1],
       [1, 3, 3, 1],
       [1, 4, 2, 3]])

In [ ]:
matris4[0]=[7,7,7,7]

In [ ]:
matris4

array([[7, 7, 7, 7],
       [2, 2, 4, 1],
       [1, 3, 3, 1],
       [1, 4, 2, 3]])

In [ ]:
matris3

array([[4, 4, 4, 0],
       [2, 2, 4, 1],
       [1, 3, 3, 1],
       [1, 4, 2, 3]])

# Ders13 - ones() , zeros() ve full() Matris Oluşturma Metotları

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

# Ders 14 - Numpy eye() diag() ve identity() Metotları

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.diag([1,2,3,2,1])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
r=np.random.randint(0,3,(5,5))
print(r)

[[1 2 1 2 1]
 [0 0 2 2 0]
 [2 0 0 2 2]
 [0 2 0 1 1]
 [0 2 2 0 2]]


In [ ]:
np.diag(r)

array([1, 0, 0, 1, 2])

In [ ]:
np.diag(np.diag(r))

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 2]])

# Ders 15 Matrislerde Matematiksel İşlemler toplama çıkarma çarpma bölme fark

In [ ]:
m1= np.ones((5,5))
m2= np.full((5,5),19)

In [ ]:
m1=m1.astype("int16")
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [ ]:
m1*4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]], dtype=int16)

In [ ]:
m2+3

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [ ]:
m2+m1

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [ ]:
m2-m1

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])

In [ ]:
m2/3

array([[6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333]])

In [ ]:
m2//3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [ ]:
m2%3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
m3=np.full((5,6),2)

In [ ]:
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [ ]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [ ]:
m3.shape

(5, 6)

In [ ]:
m2.shape

(5, 5)

In [ ]:
m2+m3

In [ ]:
m3.reshape(30)[:25].reshape(5,5)+m2

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [ ]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
m1[0]=m1[0]*3

In [ ]:
m1

array([[3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
m1

array([[3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
m5=np.arange(5).reshape((5,1))

In [ ]:
m5

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
m1*m5

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [ ]:
m1/m5

<ipython-input-91-d597fd457727>:1: RuntimeWarning: divide by zero encountered in true_divide
  m1/m5


array([[       inf,        inf,        inf,        inf,        inf],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ]])

In [ ]:
m6=m1+m5

In [ ]:
m6

array([[3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [ ]:
m6*np.diag(m6)

array([[ 9,  6,  9, 12, 15],
       [ 6,  4,  6,  8, 10],
       [ 9,  6,  9, 12, 15],
       [12,  8, 12, 16, 20],
       [15, 10, 15, 20, 25]])

# Ders 16 Numpy ile Mantıksal Operatörler ve Filtreleme

In [ ]:
matris=np.random.randint(0,10,(5,5))

In [ ]:
matris

array([[7, 2, 6, 6, 6],
       [9, 7, 0, 5, 7],
       [9, 2, 2, 0, 9],
       [9, 6, 7, 5, 9],
       [1, 4, 3, 1, 6]])

In [ ]:
matris>5

array([[ True, False,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False, False, False, False,  True]])

In [ ]:
matris[matris>5]

array([7, 6, 6, 6, 9, 7, 7, 9, 9, 9, 6, 7, 9, 6])

In [ ]:
matris[matris<5]

array([2, 0, 2, 2, 0, 1, 4, 3, 1])

In [ ]:
matris[matris>=5]

array([7, 6, 6, 6, 9, 7, 5, 7, 9, 9, 9, 6, 7, 5, 9, 6])

In [ ]:
matris[matris==5]

array([5, 5])

In [ ]:
matris[matris==7].size

4

In [ ]:
matris[matris!=7]

array([2, 6, 6, 6, 9, 0, 5, 9, 2, 2, 0, 9, 9, 6, 5, 9, 1, 4, 3, 1, 6])

In [ ]:
matris

array([[7, 2, 6, 6, 6],
       [9, 7, 0, 5, 7],
       [9, 2, 2, 0, 9],
       [9, 6, 7, 5, 9],
       [1, 4, 3, 1, 6]])

In [ ]:
matris%2==0

array([[False,  True,  True,  True,  True],
       [False, False,  True, False, False],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [False,  True, False, False,  True]])

In [ ]:
matris[matris%2==0]

array([2, 6, 6, 6, 0, 2, 2, 0, 6, 4, 6])

In [ ]:
sifir=matris!=0
cift=matris%2==0
bir=matris==1

In [ ]:
matris[cift & sifir]

array([2, 6, 6, 6, 2, 2, 6, 4, 6])

In [ ]:
matris[cift | bir]

array([2, 6, 6, 6, 0, 2, 2, 0, 6, 1, 4, 1, 6])

In [ ]:
matris[(cift & sifir) | bir]

array([2, 6, 6, 6, 2, 2, 6, 1, 4, 1, 6])

In [ ]:
matris.shape

(5, 5)

In [ ]:
m2=np.full((5,5),5)

In [ ]:
m2[(cift & sifir) | bir]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])